# Generated by Django 5.0 on 2023-12-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('fecha_registro', models.DateField()),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=600)),
                ('fecha_realizacion', models.DateField()),
                ('ubicacion', models.CharField(max_length=50)),
                ('realizado', models.BooleanField()),
            ],
        ),
    ]
